### ISSUE TITLE
Mention dates for individual issues on the portal

### ISSUE THREAD

**Issue by adityaraute** [github/forgoodfirstissue#105]
**Is your feature request related to a problem? Please describe.**
It is frustrating when we click on an issue under a repo and it has been open since 2019 with no assignee and stuff.

**Describe the solution you'd like**
I say mention the opening date of each issue so that users know which issue will really respond to their needs.

**Describe alternatives you've considered**
Alternative would be to mention the last activity dates for the `good-first-issues` only and not the entire repo, as this may be confusing.

**Comment by seanmarcia** [comment]
Hey @adityarautem, that makes sense! I can see that it would be frustrating.

Did you comment or ask if the issue was still valid or in need of help? 

My concern with implementing this is if there is a task/issue that an organization has been hoping someone would work on but, for whatever reason, no one has picked it up. I wouldn't want to turn people away from contributing somewhere where an org needs help but they decide not to because they think the issue is dead.

What do you think? Any thoughts on how we could prevent this? Ideally, it would be great if all repos implemented a GitHub action that auto-closed stale issues.

**Comment by adityaraute** [comment]
> My concern with implementing this is if there is a task/issue that an organization has been hoping someone would work on but, for whatever reason, no one has picked it up. I wouldn't want to turn people away from contributing somewhere where an org needs help but they decide not to because they think the issue is dead.

I see what you mean here. But it's not like this information is hidden anyways. Once the user opens the issue, the creation date and every other relevant detail is available to be seen.
The aim of this feature will only be to give that information a bit earlier than later, not to disclose any hidden detail. Hope that makes sense.


> Any thoughts on how we could prevent this?

Wonder if we can assign flags to each issue ranging from `very recently active` to `practically stale` by taking into account the latest update on the issue discussion. However, this may serve as a deterrent for the reasons you previously mentioned. It's a complicated problem for sure.

**Comment by seanmarcia** [comment]
Sorry for the slow reply! Recently at FOSDEM I had the opportunity to speak with the folks who maintain the DPGs and they are going to be communicating guidelines out shortly so hopefully this won't be an issue much longer. Let's circle back in a few months if things don't improve so we can try some different experiments!
